### PR TITLE
Initial add of Windows system proxy settings

### PR DESCRIPTION
**Pull request by mynamewastaken**
@rlaveycal I used your code for this, I hope that's ok.

@tmatilai This is still WIP, just wanted to get the PR made to solicit feedback. I plan to test this in the next few days.

Sorry about the mention spam, accidentally made the 1st PR against my own copy.

### CODE REVIEW

**Comment by mynamewastaken** [comment]
@tmatilai This does appear to work! I took a screenshot (http://imgur.com/taaTOEA) where that was set exclusively by the vagrant-proxyconf plugin - nothing external.

**Comment by mynamewastaken** [comment]
Will rebase and squash when I get home.

**Comment by tmatilai** [comment]
@mynamewastaken wanna squash? I'm fine merging this trusting you it's working. =)

**Comment by mynamewastaken** [comment]
@tmatilai squashed!

**Comment by tmatilai** [comment]
Great, thanks a lot!

**Pull request merged**
