### PR TITLE
Provisioning of docker fails issue 180

### PR DESCRIPTION
**Pull request by codylane**
Attempt to address #180, #181 

Overview of Bugfix/Features
-----------------------------

The vagrant-proxyconf plugin is installed
AND
no config.proxy.* are set in a Vagrantfile

```
Vagrant.configure("2") do |config|
    config.vm.provider "docker" do |d|
      d.image = "hello-world"
    end
end
```

The pull request addresses this problem by disabling the vagrant-proxyconf plugin.

## The second feature of this pull request 

Adds additional logic to check if a proxy should be configured
Given either of the following environment variables being set
`export HTTP_PROXY=http://$my_proxy_host:$my_proxy_port`
*OR*
`export HTTPS_PROXY=https://$my_proxy_host:$my_proxy_port`
*AND*
Given this `Vagrantfile`

```
Vagrant.configure("2") do |config|

    if Vagrant.has_plugin?("vagrant-proxyconf")
      config.proxy.http      = "#{ENV['HTTP_PROXY']}"
      config.proxy.https     = "#{ENV['HTTPS_PROXY']}"
      config.proxy.no_proxy  = "#{ENV['NO_PROXY']}"
    end

    config.vm.provider "docker" do |d|
      d.image = "hello-world"
    end
end
```

The `vagrant-proxyconf` plugin would be enabled for all capable providers on the guest. However, if you didn't set `HTTP_PROXY` or `HTTPS_PROXY` in your environment before running vagrant up or vagrant provision then there is new logic to disable `vagrant-proxyconf` from attempting to configure your guest.

The new logic is an attempt to _auto-configure_ the `vagrant-proxyconf` providers based off your current environment proxy variables.

### CODE REVIEW

**Comment by codylane** [comment]
@tmatilai - Thoughts on removing support for EOL ruby 2.2.5?  I have no easy way to test the failure that travis-ci is reporting.

**Comment by tmatilai** [comment]
> Thoughts on removing support for EOL ruby 2.2.5? I have no easy way to test the failure that travis-ci is reporting.

Oh my... Travis is a moving target. Dropping Ruby 2.2 would mean dropping also testing of Vagrant 1.8. Just recently I dropped the even older ones, so fine by me. Vagrant 1.9 was released over two years ago.

**Comment by codylane** [comment]
> > Thoughts on removing support for EOL ruby 2.2.5? I have no easy way to test the failure that travis-ci is reporting.
> 
> Oh my... Travis is a moving target. Dropping Ruby 2.2 would mean dropping also testing of Vagrant 1.8. Just recently I dropped the even older ones, so fine by me. Vagrant 1.9 was released over two years ago.

Roger, thanks for responding back.  I plan to remove 2.2.5 from .travis.yml sometime this weekend.

**Comment by codylane** [comment]
There is one minor use case in this pull request that I forgot to address.  

Scenario
---------

When disabling this plugin `config.proxy.enabled = false` for any proxies have been configured in the guest environment there is a still a problem that disabling the proxy doesn't "undo" any configuration that has been applied, instead it skips the provider from being configured.  The user has to remember to also set the provide specific skip option to true, which freaking confusing. 

```
{
  :apt    => {
    :enabled => true,
    :skip    => false,
  },
  :chef => {
    :enabled => true,
    :skip    => false,
  },
  :docker => {
    :enabled => true,
    :skip    => false
  },
  :env => {
    :enabled => true,
    :skip    => false,
  },
  :git => {
    :enabled => true,
    :skip    => false,
  },
  :npm => {
    :enabled => true,
    :skip    => false,
  },
  :pear => {
    :enabled => true,
    :skip    => false
  },
  :svn => {
    :enabled => true,
    :skip    => false,
  },
  :yum => {
    :enabled => true,
    :skip    => false,
  },
}
```

**Pull request merged**
