### PR TITLE
Apt proxy verify host

### PR DESCRIPTION
**Pull request by greut**
An attempt to add the following proxy options to APT. Any helps would be much appreciated.

```perl
Acquire::https::Verify-Host "false";
Acquire::https::Verify-Peer "false";
```

### CODE REVIEW

**Comment by codylane** [comment]
Thank you for your contribution.  I'll need some time to digest this pull request and or do an official code review.  

At first pass, i'm good with this and thank you for writing tests. ;) 

@tmatilai - Do you have any additional thoughts or concerns?

**Comment by greut** [comment]
@codylane at the end of the day I did that with a small `shell` provisioner. Take it only if you feel it's actually useful. It feels quite hackish.

**Comment by codylane** [comment]
hi @greut - Thanks again for reporting this.  I've not had the time to look into this issue much further and I apologize.

I just wanted to confirm that I understand this issue correctly, do the changes you are requesting help support the case when you are behind a proxy that terminates ssl and without these settings apt cannot install packages or do updates?

**Comment by greut** [comment]
@codylane indeed, a proxy that also is a mitm. An happy corporate setup we've got here :)

**Comment by codylane** [comment]
Awesome, thanks for the response. I'm going to try and get this in the 2.0.2 release.  I hope to have some time this week.

**Comment by codylane** [comment]
Hey - Status update and I apologize for the delay.  I should have some extra free time in the next couple of weeks to get this in and I've made a few changes to those core libraries which would probably make this pull request to be a little behind.  Since this is my fault for not merging this in sooner i'll take care of this problem.

I appreciate you taking the time to put this in and write tests. :)

I'll make sure this gets into the 2.0.3 release.

**Comment by codylane** [comment]
Hi @greut - I'm closing out this pull request since it's my fault this is out of date.  I'll be tracking this change via #199.  I plan to give you full credit for this in the release changelog.  I apologize for for the delay.

**Pull request closed without merging**
